The final (?) word in font searching. Sigh.
svn path=/trunk/kdegraphics/kdvi/; revision=63974

diff --git a/kpathsea/configure.in b/kpathsea/configure.in
--- a/kpathsea/configure.in
+++ b/kpathsea/configure.in
@@ -28,6 +28,19 @@ AC_FUNC_CLOSEDIR_VOID
 AC_CHECK_HEADERS(assert.h float.h limits.h memory.h pwd.h stdlib.h \
                  string.h sys/param.h unistd.h)
 
+# Unfortunately, kpathsea needs to be told at compile time where 
+# the TeX directory tree resides 
+
+echo "checking for $datadir/texmf/web2c/texmf.cnf"
+if test ! -r $datadir/texmf/web2c/texmf.cnf; then
+  { 
+  echo "configure: error. Please use the --datadir option to point to the main" 1>&2
+  echo "directory of your TeX installation, where the file web2c/texmf.cnf" 1>&2
+  echo "is found." 1>&2
+  exit -1
+  }
+fi
+
 
 dnl We would to do the klibtool stuff only in kpathsea (i.e., in
 dnl kpathsea/configure.in instead of here in common.ac), but then
